### ISSUE TITLE
prototype crop mask ows

### ISSUE THREAD

**Issue by fangfy** [digitalearthafrica/config#163]
Add prototype crop_mask_eastern product to dev ows.

Product in africa dev: crop_mask_eastern
bands: mask, prob

Display style:
mask band: green/yellow for 1, transparent for 0
(e.g. similar to https://croplands.org/app/map?lat=1.62576&lng=36.07910156250001&zoom=6)
reversed mask: grey for 0, transparent for 1
prob band: plasma or magma for a range 50 -100.

**Comment by pindge** [comment]
not sure what you mean by `green/yellow` for 1? like `green/yellow` the color? do you have a hexcode color for preference?

Grey I will use #cccccc, or would you like a different shade of grey?

Please provide hexcode for plasma and magma? not sure if they have universal color code for that name.

**Comment by cbur24** [comment]
I think by green/yellow we mean provide two different styling options, one that uses greens and one that uses yellows.
So for the MASK band these would be the options:
1. Light Green (e.g. `#00ff00`) where MASK==1, transparent where MASK == 0
2. Light Yellow (e.g. `#FFFF00`) where MASK==1, transparent where MASK == 0
3. "Reversed": Grey where MASK==0, transparent where MASK==1

For the PROB band  (which has continuous values):
1. Use the 'magma' perceputally uniform colour ramp. There is a QGIS xml version of it [here](https://gist.github.com/cossatot/6fd455d6a2e0e1fdb8ed547dd2176eae). Matplotlib discussion of it [here](https://matplotlib.org/3.1.0/tutorials/colors/colormaps.html))
