### ISSUE TITLE
ows - wofs summary legend

### ISSUE THREAD

**Issue by fangfy** [digitalearthafrica/config#238]
This legend label for annual summary has been broken for a while:
https://ows.digitalearth.africa/legend/wofs_2_annual_summary_frequency/WOfS_frequency/legend.png

More importantly, we should fix it before new wofs annual summary becomes available:
https://ows.dev.digitalearth.africa/legend/wofs_ls_summary_annual/wofs_summary_annual_frequency/legend.png

**Comment by SpacemanPaul** [comment]
I believe this has been fixed (by setting tick limits as numeric strings instead of floats.)
