### ISSUE TITLE
ows refactored inconsistencies compare to ows africa

### ISSUE THREAD

**Issue by pindge** [digitalearthafrica/config#38]
| issue |      ows refactor |  ows africa  | action - accept difference or fix |
|----------|-------------|------|------------|
| 1. band values |  [link](https://ows-configrefactor.digitalearth.africa/?time=2019-06-28&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=ls_usgs_fc_scene&bbox=3338769.395496499%2C-250407.70466223732%2C3339075.1436096393%2C-250101.95654909685&width=256&height=256&query_layers=ls_usgs_fc_scene&x=208&y=5&info_format=application%2Fjson) |  [link](https://ows.digitalearth.africa/?time=2019-06-28&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=ls_usgs_fc_scene&bbox=3338769.395496499%2C-250407.70466223732%2C3339075.1436096393%2C-250101.95654909685&width=256&height=256&query_layers=ls_usgs_fc_scene&x=208&y=5&info_format=application%2Fjson) | - [x] Accept - [x] Fix |
| 2. band values |   [link](https://ows-configrefactor.digitalearth.africa/?time=2019-06-28&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=ls_usgs_fc_scene&bbox=2504688.542848654%2C-1252344.271424327%2C3757032.814272985%2C0&width=256&height=256&query_layers=ls_usgs_fc_scene&x=144&y=23&info_format=application%2Fjson) |   [link](https://ows.digitalearth.africa/?time=2019-06-28&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=ls_usgs_fc_scene&bbox=2504688.542848654%2C-1252344.271424327%2C3757032.814272985%2C0&width=256&height=256&query_layers=ls_usgs_fc_scene&x=144&y=23&info_format=application%2Fjson)  | - [x] Fixed |
| 3. band values |  [link](https://ows-configrefactor.digitalearth.africa/?time=2017-06-15&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=alos_palsar_mosaic&bbox=5097432.542281833%2C1604566.0977624208%2C5098655.534734398%2C1605789.0902149826&width=256&height=256&query_layers=alos_palsar_mosaic&x=145&y=45&info_format=application%2Fjson) |     [link](https://ows.digitalearth.africa/?time=2017-06-15&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=alos_palsar_mosaic&bbox=5097432.542281833%2C1604566.0977624208%2C5098655.534734398%2C1605789.0902149826&width=256&height=256&query_layers=alos_palsar_mosaic&x=145&y=45&info_format=application%2Fjson) | - [x] Fixed |
| 4. band values |  [link](https://ows-configrefactor.digitalearth.africa/?time=2017-06-15&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=alos_palsar_mosaic&bbox=2504688.542848654%2C0%2C5009377.085697312%2C2504688.542848654&width=256&height=256&query_layers=alos_palsar_mosaic&x=71&y=192&info_format=application%2Fjson) |  [link](https://ows.digitalearth.africa/?time=2017-06-15&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=alos_palsar_mosaic&bbox=2504688.542848654%2C0%2C5009377.085697312%2C2504688.542848654&width=256&height=256&query_layers=alos_palsar_mosaic&x=71&y=192&info_format=application%2Fjson) | - [x] Fixed |
| 5. derived band values |  [link](https://ows-configrefactor.digitalearth.africa/?time=2018-01-01&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=red&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=ga_ls8c_gm_2_annual&bbox=1565430.3392804079%2C1565430.3392804079%2C1878516.4071364924%2C1878516.4071364924&width=256&height=256&query_layers=ga_ls8c_gm_2_annual&x=235&y=165&info_format=application%2Fjson)  |  [link](https://ows.digitalearth.africa/?time=2018-01-01&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=red&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=ga_ls8c_gm_2_annual&bbox=1565430.3392804079%2C1565430.3392804079%2C1878516.4071364924%2C1878516.4071364924&width=256&height=256&query_layers=ga_ls8c_gm_2_annual&x=235&y=165&info_format=application%2Fjson)  | - [x] Fixed |
| 6. image size |  [link](https://ows-configrefactor.digitalearth.africa/?time=2018-01-01&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=nir&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetMap&layers=ga_ls8c_gm_2_annual&bbox=2504688.542848654%2C-5009377.085697312%2C5009377.085697312%2C-2504688.542848654&width=256&height=256)  |  [link](https://ows.digitalearth.africa/?time=2018-01-01&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=nir&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetMap&layers=ga_ls8c_gm_2_annual&bbox=2504688.542848654%2C-5009377.085697312%2C5009377.085697312%2C-2504688.542848654&width=256&height=256)  | -  [x] Fixed |
   | 7. image size | [link](https://ows-configrefactor.digitalearth.africa/?time=2018-01-01&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetMap&layers=wofs_annual_summary_wet&bbox=3130860.6785608195%2C-313086.06785608083%2C3287403.71248886%2C-156543.03392804042&width=256&height=256) | [link](https://ows.digitalearth.africa/?time=2018-01-01&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetMap&layers=wofs_annual_summary_wet&bbox=3130860.6785608195%2C-313086.06785608083%2C3287403.71248886%2C-156543.03392804042&width=256&height=256) | - [x] Fixed |
| 8. image size | [link](https://ows-configrefactor.digitalearth.africa/?time=2013-01-01&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetMap&layers=wofs_2_annual_summary_statistics&bbox=626172.1357121654%2C313086.06785608083%2C782715.1696402058%2C469629.10178412125&width=256&height=256)  | [link](https://ows.digitalearth.africa/?time=2013-01-01&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetMap&layers=wofs_2_annual_summary_statistics&bbox=626172.1357121654%2C313086.06785608083%2C782715.1696402058%2C469629.10178412125&width=256&height=256)  | - [x] Accept - [x] Fix|
| 9. image size | [link](https://ows-configrefactor.digitalearth.africa/?time=2019-09-09&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetMap&layers=srtm&bbox=2817774.6107047386%2C-156543.03392804042%2C2974317.644632779%2C0&width=256&height=256) | [link](https://ows.digitalearth.africa/?time=2019-09-09&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetMap&layers=srtm&bbox=2817774.6107047386%2C-156543.03392804042%2C2974317.644632779%2C0&width=256&height=256) | - [x] Fixed test case  |
| 10. image size | [link](https://ows-configrefactor.digitalearth.africa/?time=2018-01-01&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetMap&layers=wofs_annual_summary_dry&bbox=3199348.2559043355%2C-293518.18861507624%2C3209132.1955248415%2C-283734.24899457395&width=256&height=256)  | [link](https://ows.digitalearth.africa/?time=2018-01-01&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetMap&layers=wofs_annual_summary_dry&bbox=3199348.2559043355%2C-293518.18861507624%2C3209132.1955248415%2C-283734.24899457395&width=256&height=256) | - [x] Fixed |
| 11. image size | [link](https://ows-configrefactor.digitalearth.africa/?time=2018-01-01&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetMap&layers=wofs_annual_summary_statistics&bbox=3214024.1653350927%2C-259274.39994331822%2C3218916.135145344%2C-254382.43013306707&width=256&height=256) | [link](https://ows.digitalearth.africa/?time=2018-01-01&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetMap&layers=wofs_annual_summary_statistics&bbox=3214024.1653350927%2C-259274.39994331822%2C3218916.135145344%2C-254382.43013306707&width=256&height=256) | - [x] Fixed |
| 12. Derived band | [link](https://ows-configrefactor.digitalearth.africa/?time=2018-01-01&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=ndwi&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=ga_ls8c_gm_2_annual&bbox=3757032.814272985%2C-2504688.542848654%2C5009377.085697312%2C-1252344.271424327&width=256&height=256&query_layers=ga_ls8c_gm_2_annual&x=31&y=161&info_format=application%2Fjson) | [link](https://ows.digitalearth.africa/?time=2018-01-01&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=ndwi&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=ga_ls8c_gm_2_annual&bbox=3757032.814272985%2C-2504688.542848654%2C5009377.085697312%2C-1252344.271424327&width=256&height=256&query_layers=ga_ls8c_gm_2_annual&x=31&y=161&info_format=application%2Fjson) | - [x] Fixed |

**Comment by tom-butler** [comment]
Hey @pindge I've reviewed all the image ones, I'd try and look into those and see if they change the band values, as they are harder to review.

So far I'm not happy with these changes, so we should try and fix them before deploying. 

6. Image size (you're comparing an overview to an actual image, need to confirm the min_zoom_size is the same on both config)
7. looks like either changes in overview algorithm (average vs nearest, or different flags in the style)
8. Looks like the style is wrong, this style shouldn't have any green in it.
9. Default style could have changed? you're not passing a style through so it'll render the default style. or the colours for the style are different
10. This one is a bit weird, looks like either the location / time is different, or the fuse-function has changed
11. Looks like it's comparing two different years, or the overview is average instead of nearest, maybe different flags for terrain too.
