### ISSUE TITLE
ALOS styling

### ISSUE THREAD

**Issue by fangfy** [digitalearthafrica/config#93]
To improve ALOS styling in ows_cfg.py
1. For hh_hv_hv_over_hh, apply following stretching (scale range?) per-band:
```
hh: [500, 10000]
hv: [200, 4000]
hv/hh:  [0.1, 1.0]
```
2. style_alos_hh_over_hv is not necessary.
3. If possible, add a Radar Vegetation Index band, which is (4*hv^2)/(hh^2+hv^2), with scale range [0.2, 1] and 'viridis' colormap.

**Comment by pindge** [comment]
hi Fang,

I don't know what that maths formula bit means, what do i do with it?

**Comment by pindge** [comment]
This is ready to be closed.
