### ISSUE TITLE
Adding JERS mosaic

### ISSUE THREAD

**Issue by fangfy** [digitalearthafrica/config#94]
The JERS mosaic (currently product "jers_mosaic", but maybe reindexed to be "jers_sar_mosaic") should be added to ows_cfg.py using information from the metadata catalog. Only one display style for hh is needed. Jers hh digital numbers have a scaling ~1.21 (10^0.083) times ALOS hh digital numbers. Therefore the alos_hh color ramp with all values x 1.21 will work.

**Comment by pindge** [comment]
```
jers_sar_tile                  JERS-1 SAR annual mosaic tiles generated for use in the Data Cube - 25m pixel spacing, WGS84. These tiles are derived from the orignal JAXA mosaics with conversion to GeoTIFF.
```
Is this it, this is the only on there

**Comment by fangfy** [comment]
yes, that's the correct one
