### ISSUE TITLE
Landsat 8 geomedian styling

### ISSUE THREAD

**Issue by fangfy** [digitalearthafrica/config#95]
The provisional landsat 8 (collection 2) data has a scaling and an offset, so Surface Reflectance = DN  * 2.75e-5 - 0.2. The default band indices calculations are therefore incorrect. 
The NDVI/NDWI/MNDWI layers for the Landsat 8 Geomedian should be removed or updated (using customized functions).

**Comment by whatnick** [comment]
Given this is provisional data we are doing to down-prio fixing this for now.

**Comment by fangfy** [comment]
To be clear, I'm happy for these stylings to be removed for now, instead of fixed. This will needs fixing after usgs collection 2 is available and if the same scaling and offset apply.
